GET http://localhost:3000/api/workouts
###

POST http://localhost:3000/api/workouts HTTP/1.1
content-type: application/json


{
    "day": "2021-04-16T20:13:47.242Z",
    "exercises": [{
        "type": "Resistance",
            "name": "Bench Press",
            "duration": 10,
          "weight": 50,
          "reps": 5,
          "sets": 15
    }]
  }

###